### ISSUE TITLE
Return player name in the now-playing subcommand

### ISSUE THREAD

**Issue by mradermaxlol** [ray-kast/empress#3]
As far as I can tell, `empress now-playing` returns just 4 json values, no more & no less (unless I'm missing something):
![image](https://user-images.githubusercontent.com/11138966/156151016-4d500277-abe4-4efc-94c0-d852656652a6.png)

It would be nice to have the active player title returned as well, similar to `playerctl metadata`.

On a side note: is the `"artist"` field supposed to be an array?

**Comment by ray-kast** [comment]
Fix for this is pushed, I'll get a version rolled out with it once I'm done with the now-playing formatter.

**Comment by ray-kast** [comment]
This feature is now [out in beta](https://github.com/ray-kast/empress/releases/tag/v1.6.0-beta.1).  I've pushed a build to [crates.io](https://crates.io/crates/empress/1.6.0-beta.1) for testing.
